version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "8080:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dWsU2J83S7!X
    ports:
      - "27017:27017"

  redis:
    image: redis
    
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile.Api
    container_name: customer-profile-api
    ports:
      - "80:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
      redis:
        condition: service_started
    environment:
      RabbitMQConnectionString: "amqp://guest:guest@rabbitmq:5672"
      RedisConnectionString: "redis"
      ViaCep: "https://viacep.com.br/ws"
      MongoDbConnectionString: "mongodb://root:dWsU2J83S7!X@mongodb:27017"
      DatabaseName : "CustomerProfile"
      
  azure-functions:
    build: 
      context: ./Api
      dockerfile: DockerFile.AzureFunction
    container_name: customer-profile-azure-functions
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
      redis:
        condition: service_started
    environment:
      RabbitMQConnectionString: "amqp://guest:guest@rabbitmq:5672"
      RedisConnectionString: "redis"
      ViaCep: "https://viacep.com.br/ws"
      MongoDbConnectionString: "mongodb://root:dWsU2J83S7!X@mongodb:27017"
      DatabaseName : "CustomerProfile"