version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: Gyrte689uiw
    ports:
      - "8080:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dWsU2J83S7!X
    ports:
      - "27017:27017"

  redis:
    image: redis
  
  api:
    build:
      context: ./Api
      dockerfile: Dockerfile.Api
    container_name: customer-profile-api
    ports:
      - "5021:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
      redis:
        condition: service_started
    environment:
      RabbitMQConnectionString: "amqp://root:Gyrte689uiw@rabbitmq:5672"
      RedisConnectionString: "redis"
      ViaCep: "https://viacep.com.br/ws"
      MongoDbConnectionString: "mongodb://root:dWsU2J83S7!X@mongodb:27017"
      DatabaseName : "CustomerProfile"
      SlatKey: "D*Ezu1hl612."
      Key: "S07R6/cLJct0Oq0OK3aXcA=="
      Iv: "sTZAYMb9P9TCCfLAAMCcvQ=="

  azure-functions:
    build: 
      context: ./Api
      dockerfile: DockerFile.AzureFunction
    container_name: customer-profile-azure-functions
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
      redis:
        condition: service_started
      azure-storage:
        condition: service_started
      configure-rabbit:
        condition: service_completed_successfully
    environment:
      RabbitMQConnectionString: "amqp://root:Gyrte689uiw@rabbitmq:5672"
      RedisConnectionString: "redis"
      ViaCep: "https://viacep.com.br/ws"
      MongoDbConnectionString: "mongodb://root:dWsU2J83S7!X@mongodb:27017"
      DatabaseName : "CustomerProfile"
      AzureWebJobsStorage: "DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://local.storage.emulator:10000/devstoreaccount1;QueueEndpoint=http://local.storage.emulator:10001/devstoreaccount1;"
      SlatKey: "D*Ezu1hl612."
      Key: "S07R6/cLJct0Oq0OK3aXcA=="
      Iv: "sTZAYMb9P9TCCfLAAMCcvQ=="

  azure-storage:
    image: "mcr.microsoft.com/azure-storage/azurite:latest"
    container_name: azure-storage
    ports:
        - 10000:10000
        - 10001:10001      

  configure-rabbit:
    build:
      context: ./Configuration
      dockerfile: Dockerfile
    container_name: configure-rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      user: "root"
      password: "Gyrte689uiw"
      host: rabbitmq
      port: 5672           