@startuml container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_LANDSCAPE()
TITLE Customer Profile Center - Container

AddRelTag("async", $lineStyle= DashedLine())

Person(customer, "Cliente", "Consumidor final que foi cadastrado no sistema")

Boundary(internalProducersBoundary, "Sistemas internos") {
    Container(marketingPlatform, "Landing Page - Marketing", "Vue.js", "Landing page para obter novos clientes")
    Container(marketingPlatformBff, "BFF Plataforma De Marketing", "Node Js", "Responsável por centralizar as chamadas para as APIs")
    Container(pdvPlatforma, "PDV", "Windows Forms C#", "Plataforma de manipulação de vendas nas lojas físicas")
    Container(ecomerPlatform, "E-Comerce", "Vue.js", "Plataforma de e-comerce")
}


Boundary(customerProfileCenterBoundary, "Customer Profile Center") {
    ContainerQueue(rabbitCustomer, "Serviço de Mensageria", "RabbitMQ", "Pedido de criação de um cliente")

    Container(customerProfileCenter, "Customer Profile Center API","ASP NET 7", "Recebe pedidos de criação de clientes via HTTP")
    Container(customerProfileCenterFunction, "Customer Profile Center Function", "Azure Function 4",  "Responsável por criação de novos clientes")
    ContainerDb(customerProfileDb, "Customer Profile Database", "MongoDB", "Armazena os dados dos consumidores")

    Container(reportSystem, "Report System","ASP NET 7", "Centraliza os dados dos clientes para relatórios")
    ContainerDb(reportingDb, "Reporting Database", "SQL Server", "Armazena dados para geração de relatórios avançados")
    ContainerQueue(rabbitMqReport, "Serviço de Mensageria", "RabbitMQ", "Dados de criação de um cliente")

    Container(notificationCenter, "Notification Center", "ASP NET 7",  "Responsável por notificações dos clientes")
    ContainerQueue(rabbitMqNotification, "Serviço de Mensageria", "RabbitMQ", "Dados de Notificação")
    System_Ext(emailService, "Sistema de Email", "Sitema de controle de template e envio de email")
    System_Ext(phoneService, "Sistema de envio \n SMS / Whatsapp", "Sitema de envio de notificações para celulares", "HTTP/JSON")

    System_Ext(viaCep, "ViaCEP", "Sistema Externo para obter informações sobre CEP")
    Container(cepService, "Cep Service", "Sistema para obter informações sobre CEP")
    ContainerDb(platformCache, "In-memory data store", "Redis", "Usado para armazenar os dados de forma temporária. Cache.")
}

'Relacionamento dos clientes
Rel(marketingPlatform, marketingPlatformBff, "Envia Dados de Cadastro e Busca dados para construção da tela", "HTTP/JSON")
Rel(marketingPlatformBff, customerProfileCenter, "Envia Pedido de Cadastro De Cliente", "HTTP/JSON")
Rel(marketingPlatformBff, cepService, "Busca dados de CEP para preencher na tela", "HTTP/JSON")

Rel(pdvPlatforma, rabbitCustomer, "Envia Pedido de Cadastro De Cliente", "AMQP", $tags = "async")
Rel(ecomerPlatform, rabbitCustomer, "Envia Pedido de Cadastro De Cliente", "AMQP", $tags = "async")

'Relacionamentos com o Customer Profile
Rel(customerProfileCenter, customerProfileDb, "Busca dados para validações no", "HTTP/JSON")
Rel(customerProfileCenter, rabbitCustomer , "Envia Pedido de Cadastro De Cliente", "AMQP", $tags = "async")
Rel(rabbitCustomer, customerProfileCenterFunction , "Envia Pedido de Cadastro De Cliente", "AMQP", $tags = "async")
Rel(customerProfileCenterFunction, customerProfileDb, "Armazena / Busca dados para validação os dados no", "")
Rel(customerProfileCenterFunction, cepService, "Busca Dados para preencher Endereço", "HTTP/JSON")
Rel(customerProfileCenterFunction, rabbitMqReport, "Adiciona dados do Cliente criado no Topico", "AMQP", $tags = "async")

'Relacionamentos do reportSystem
Rel(reportSystem, reportingDb, "Armazena os dados no", "")
Rel(rabbitMqReport, reportSystem, "Envia dados do cliente para", "AMQP", $tags = "async")

'Relacionamentos do sistema de Cep
Rel(cepService, viaCep, "Busca dados no", "HTTP/JOSN")
Rel(cepService, platformCache, "Armazena e faz leitura de Cache No")

'Relacionamentos com os sistemas de notificação
Rel(customerProfileCenterFunction, rabbitMqNotification, "Enfileira Notificação no", "AMQP", $tags = "async")
Rel(rabbitMqNotification, notificationCenter, "Envia Mensagem para", "AMQP", $tags = "async")
Rel(notificationCenter, emailService, "Envia Notificação usando", "HTTP/JSON")
Rel(notificationCenter, phoneService, "Envia Notificação usando", "HTTP/JSON")
Rel(emailService, customer, "Notifica Cliente", "")
Rel(phoneService, customer, "Notifica Cliente", "")

SHOW_LEGEND()
@enduml