services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - .~/CustomerProfileCenter/Configuration/ReverseProxy/nginx/conf/:/etc/nginx/nginx.conf
      - .~/certbot/www:/var/www/certbot/nginx.conf.
      - ~/certbot/conf/:/etc/nginx/ssl/
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ~/certbot/www/:/var/www/certbot/:rw
      - ~/certbot/conf/:/etc/letsencrypt/:rw